config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :photos do
    member do
      post :to_work
      post :to_cancel
      post :to_ready
      post :to_pay
    end
    collection do
      post :ready_image
    end
  end
  devise_for :users
  root 'pages#landing'
  get 'pages/about'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :ready_image, ReadyImageUploader

  has_secure_token :token
  belongs_to :user

  validate :price_for_unverified

  include AASM
  aasm do
    state :unverified, initial: true     
    state :verified                     
    state :work
    state :work_ready                   
    state :payment                    
    state :cancel                                    

    event :verify do
      transitions from: [:unverified], to: :verified
    end

    event :to_cancel do
      transitions from: [:unverified, :verified], to: :cancel
    end

    event :reverify do
      transitions from: [:verified], to: :unverified
    end

    event :to_work do
      transitions from: [:verified], to: :work
    end

    event :to_ready do
      transitions from: [:work], to: :work_ready
    end

    event :to_pay do
      transitions from: [:work_ready], to: :payment
    end

    event :pay_to do
      transitions from: [:payment], to: :work_ready
    end
  end

  private

  def price_for_unverified
    errors.add(:base, I18n.t(:change_status_verified)) if aasm_state != 'unverified' && price.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_locale
	 
	def set_locale
	  I18n.locale = params[:locale] || I18n.default_locale = :ru
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    if user_signed_in?
      redirect_to "/photos"
    end
  end

  def about
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy, :to_work, :to_cancel, :to_pay]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :owner, only: [:edit, :update, :destroy]

  def index
    @photos = current_user.photos.order(id: :desc).page(params[:page])
    @description = 'Description of Charge'
    @q = Photo.ransack(params[:q])
  end   

  def show
  end

  def new 
    @photo = current_user.photos.build
  end

  def edit
  end

  def create 
    @photo = current_user.photos.build(photo_params)
    if @photo.save
      redirect_to @photo, notice: t(:photo_create)
    else
      render :new
    end
  end

  def ready_image 
    @photo = Photo.find_by(token: params[:token])
    if @photo
      send_file @photo.ready_image.path,
                type: 'image/jpg',
                disposition: 'attachment'
    else
      errors.add(:base, I18n.t(:not_image))
    end    
  end

  def to_work
    @photo.to_work! if !@photo.work?
    redirect_to @photo
  end

  def to_cancel
    @photo.to_cancel! if !@photo.cancel?
    redirect_to @photo
  end

  def to_pay
    @customer = Stripe::Customer.create(email: params[:stripeEmail],
                                        source: params[:stripeToken])
    return redirect_to @photo if !@customer.present?
    @charge = Stripe::Charge.create(customer: @customer.id,
                                    amount: (@photo.price * 100).to_i,
                                    description: 'Rails Stripe customer',
                                    currency: 'rub')
    @photo.to_pay!
    redirect_to @photo
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to @photo
  end

  def update
    if @photo.update(photo_params)
      redirect_to @photo, notice: t(:photo_update)
    else
      render :edit
    end
  end

  def destroy
    if @photo.destroy
      redirect_to photos_path, notice: t(:photo_delete)
    end
  end

  private

  def owner      
    @photo = current_user.photos.find_by(id: params[:id])
      redirect_to photos_path, notice: t(:you_do_not_photo) if @photo.nil?
  end
  
  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:description, :image, :update, :price, :aasm_state, :ready_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_navigation.html.slim
- if user_signed_in?
  nav.navbar.navbar-expand-lg.navbar-light[style="background-color: #255bb2;"]
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    .container
      #navbarTogglerDemo01.collapse.navbar-collapse
        = link_to t('.home_page'), root_path, class:'navbar-brand text-logotipe'
        ul.navbar-nav.mr-auto.mt-2.mt-lg-0
          li.nav-item
            = link_to current_user.email, edit_user_registration_path, class:'nav-link'
          li.nav-item
            = link_to t('.logout'), destroy_user_session_path, method: :delete, class:'nav-link'
- else
  nav.navbar.navbar-expand-lg.navbar-light.bar-image
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    .container
      #navbarTogglerDemo01.collapse.navbar-collapse
        = link_to t('.home_page'), root_path, class:'navbar-brand text-logotipe landing-logotipe'
        ul.navbar-nav.mr-auto.mt-2.mt-lg-0
          li.nav-item
            = link_to t('.about_the_project'), pages_about_path, class:'nav-link'
          li.nav-item
            = link_to t('.login'), new_user_session_path, class:'nav-link'
          li.nav-item
            = link_to t('.admin'), admin_user_session_path, class:'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('.my_app')
    = csrf_meta_tags
    = csp_meta_tag
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  body
    - if user_signed_in?
      .container-fluid.container-bar

    - else
      .container-fluid.container-bar

    = render "layouts/navigation"
    .container
      p.notice
        = notice
      p.alert
        = alert
      = yield
  body

app/views/pages/about.html.slim
.jumbotron.jumbotron-landing
  h1.display-4
    | О проекте!
  p.lead
  p
  h3
    | Общая суть.
  |  Необходимо реализовать приложение которое поможет художнику общаться с заказчиком и выполнять его работы. В общем виде процесс выглядит следующим образом. Заказчик на сайте художника после регистрации создает заказ к которому прикрепляет изображение с указанием того что необходимо с ним сделать. Заказ имеет несколько статусов которые он проходит в процессе работы. 
  br
  |  1. Новый - созданный заказ, еще не оцененный художником
  br
  |  2. Оцененный - заказ который оценил художник и проставил для него цену
  br
  |  3. В работу - заказчик согласился с ценой
  br
  |  4. Проверка - художник сделал работу и прикрепил ее к задаче (нюансы чуть ниже)
  br
  |  5. Оплаченный - завершенный заказ.
  br
  |  Хитрость в том что художник после завершения работы прикладывает работу (картинку) в заказу но заказчик не может ее скачать до того момента пока не оплатит, а только видит thumbnail (маленькую картинку) ну или картинку с водяными знаками. После оплаты заказа картинка становится доступна без ограничений.
  br
  |  Необходимый функционал (через дефис я указывал гемы которым следует его реализовывать): 
  br
  |  1. Регистрация/авторизация для заказчика - devise 
  br
  |  2. Админка, базовая без излишеств, в ней будет работать только художник - activeadmin
  br
  |  3. Возможность загружать и хранить картинки - carrierwave
  br
  |  * возможность выгружать картинки на S3 - это пока оставим под звездочкой, посмотрим как у тебя пойдет если проблем не будет попробуем реализовать
  br
  |  4. Платежи - stripe, это тоже лучше прикрутить после базового функционала.
  br
  |  5. Интерфейс приложения - bootstrap, с ним верстка не должна занять много времени. Помимо админки хватит пары страниц для взаимодействия с заказчиком
  br
  |  Замечания: Страницы верстай сразу в slim, он сейчас на 80% проектов, для CSS используй saas либо scss. Ну и javascript если до него дойдет лучше все делать в coffee. В целом будет работать и по-старинке но все что я перечислил относится к “глазури” и позволяет ускорить разработку довольно прилично 
  p.main_part
    | приложение Rails v5.2.1

app/views/pages/landing.html.slim
- if user_signed_in?
- else
  .jumbotron
    h1.display-4
      = t('.hello_friends')
    p.lead
      = t('.orders_pictures')
    hr.my-4
    = link_to t('.registration'), new_user_registration_path, class: "btn btn-warning"
    = link_to t('.login'), new_user_session_path, class: "btn btn-primary"
  p.main_part

app/views/photos/_form.html.slim
= form_for photo, html: { multipart: true } do |form|
  - if photo.errors.any?
    #error_explanation
      h2
        = pluralize(photo.errors.count, "error")
        |  prohibited this photo from being saved:
      ul
        - photo.errors.full_messages.each do |message|
          li
            = message  
  .form-group
    = form.label :image
    = form.file_field :image, class: "form-control"
  .form-group
    = form.label t('.description')
    = form.text_field :description, class: "form-control"
  .actions
    = form.submit t('.to_order'), class:"btn btn-primary"

app/views/photos/_search_form.html.slim
= search_form_for @q do |f|

app/views/photos/create.html.slim
h2
  | Thanks, you paid 
  strong
    = number_to_currency(@photo.amount / 100)
  | ! 
h3
  | Stripe Customer
= debug @customer
h3
  | Stripe Charge
= debug @charge

app/views/photos/edit.html.slim
.card.photo-form
  .card-header
    h2
      = t('.change_order')
  .card-body
    = render 'form', photo: @photo
    | 
    = link_to t('.back'), photos_path

app/views/photos/index.html.slim
= render 'search_form'

- @photos.each do |photo|
  .card.photo-form
    .card-body
      = image_tag photo.image.url(:little)
      br
      strong
        = photo.description
      br
        = number_to_currency(photo.price)
        br
          = photo.aasm_state
        = photo.user.email if photo.user
      br
       
        |  
        = link_to t('.to_work'), to_work_photo_path(photo), method: :post if photo.aasm_state == 'verified'
      tl
        = link_to t('.to_show'), photo, method: :get if ['work_ready', 'payment'].include?(photo.aasm_state)
        |  
        = link_to t('.cancel'), to_cancel_photo_path(photo), method: :post if photo.aasm_state == 'verified'
        |  | 
        = link_to t('.to_change'), edit_photo_path(photo) if photo.aasm_state == 'verified'
        |  | 
        = link_to t('.remove'), photo_path(photo), method: :delete, data: { confirm: t('.are_you_sure?') }
br

  = link_to t('.new_order'), new_photo_path, class:"btn btn-primary"

= paginate @photos, theme: 'twitter-bootstrap-4',
                   pagination_class: "pagination-lg"

app/views/photos/new.html.slim
.card.photo-form
  .card-header
    h2
      = t('.to_produce_new_order')
  .card-body
    = render 'form', photo: @photo
    = link_to t('.back'), photos_path

app/views/photos/show.html.slim
.card.photo-form
  .card-body
    p
      = image_tag @photo.image.url (:little)
      br
      strong
        = @photo.description        
      br
        = number_to_currency(@photo.price)
        br
        = @photo.aasm_state

      = @photo.user.email if @photo.user
      br
      |
      - if @photo.aasm_state == 'work_ready'
        = form_tag to_pay_photo_path(@photo), method: :post do 
          script.stripe-button data-amount=(@photo.price * 100) data-currency=('rub') data-description=t('.payment_was_successful') data-key="#{Rails.configuration.stripe[:publishable_key]}" data-locale="auto" src="https://checkout.stripe.com/checkout.js"
      |
      = link_to t('.download_image'), ready_image_photos_path(token: @photo.token), method: :post if 'payment'.include?(@photo.aasm_state)
      |
      = link_to t('.to_change'), edit_photo_path(@photo) if ['unverified', 'verified', 'work'].include?(@photo.aasm_state)
      |  | 
      = link_to t('.remove'), @photo, method: :delete, data: { confirm: t('.are_you_sure?') }
      |  | 
      = link_to t('.back'), photos_path